### ISSUE TITLE
Daily server restart

### ISSUE THREAD

**Issue by ducklul** [crux-f/atrium-issues#3]
**Is your feature request related to a problem? Please describe.**
The server can get a wee bit laggy sometimes.

**Describe the solution you'd like**
A fix to this could be a daily restart at a time when there wouldn't be players online. This would help keep the ram usage lower so it wouldn't cause as much lag.

**Describe alternatives you've considered**
The only thing I could think of would be a ram upgrade on the server but I don't think that is possible at the moment.

**Comment by crux-f** [comment]
A good idea! Implemented.
