### ISSUE TITLE
[Bug] Trade Agreements aren't working

### ISSUE THREAD

**Issue by crux-f** [crux-f/atrium-issues#4]
**Describe the issue**
Pressing Use on a Master level villager with a Trade Agreement (purchased from a Merchant) currently consumes the agreement but doesn't do anything else.

**To Reproduce**
1. Acquire a Trade Agreement by purchasing one from a Merchant specialist
2. Press "Use" (default is right-click) on a Villager that is Master level (diamond badge)
3. Item is consumed with no effect

**Expected behavior**
Village unlocks a trade to buy a Shipment item

**Screenshots**
N/A

**Time**
Any time. Tried with a master level Armorer and Fletcher.

**Comment by ElderShrimp** [comment]
Update: trade agreements do work but only on specialists

Fix:
Add override tag in trade agreement function

**Comment by crux-f** [comment]
Fixed using the method mentioned by ElderShrimp above; Worked as expected.
