### ISSUE TITLE
Collector Specialist wont buy Memory Vial Curiosity

### ISSUE THREAD

**Issue by ElderShrimp** [crux-f/atrium-issues#5]
**Describe the issue**
The Collector Specialist wont buy Memory Vial Curiosity even though he offers the trade

**To Reproduce**
1. Level Collector until trade is available 
2.  Attain Memory Vial curiosity
3.  Offer Memory Vial
4. Nothing Happens

**Expected behavior**
Should be buying the Memory Vial for 24 Emeralds

**Screenshots**
![2024-02-10_15 22 10](https://github.com/crux-f/atrium-server/assets/103397454/3537eb7a-8606-4376-83d8-1a33d3a48a09)
![2024-02-10_15 22 14](https://github.com/crux-f/atrium-server/assets/103397454/cf702d5c-791e-4eb7-bd43-a0416a55b430)

**Time**
2/10/2024 3:25pm

**Comment by crux-f** [comment]
This issue was caused by the Memory Vial item having the `color` specified as `yellow` even though it is yellow by default.
To ensure this will still work with existing items, I have updated the trade to make this unnecessary color change as well.
The issue is resolved.

**Comment by crux-f** [comment]
As a note, this issue will only be fixed with new Collectors that get this trade - Existing villagers would need to be manually updated, so contact an Admin and we can do this on a case-by-case basis if needed.
