### ISSUE TITLE
Calm Crystal Infusion Formula doesn't work. [Bug]

### ISSUE THREAD

**Issue by ducklul** [crux-f/atrium-issues#6]
**Describe the issue**
I put the correct recipe in for the Calm Crystal and when I click the button it doesn't get created.

**To Reproduce**
1. Put the correct recipe in for the Calm Crystal
2. Nothing happens 

(If you aren't sure exactly how it happened, describe what you were doing when the issue occurred instead)

**Expected behavior**
After pressing the button the end stone frame is supposed to create the Calm Crystal for me to pickup.

**Screenshots**
[this is a link to a video showing the bug.](https://streamable.com/blv5t2)
![2024-02-12_16 52 26](https://github.com/crux-f/atrium-server/assets/130726449/b96c12ae-d7e2-4e8e-b0c8-48d720af1a40)
![2024-02-12_16 52 42](https://github.com/crux-f/atrium-server/assets/130726449/62099087-f706-40ee-ab4f-76bf979410b0)

**Time**
2/12/2024 at 4:40 PM EST

**Additional context**

**Comment by crux-f** [comment]
Issue invalid; Recipe was upside-down.
Since we both missed that the first time, I "fixed" the issue and had to undo it.
