### ISSUE TITLE
[Bug] Magic plugin not working

### ISSUE THREAD

**Issue by ducklul** [crux-f/atrium-issues#9]
**Describe the issue**
All of the magical items I have don't seem to be working for me, dumbspacepotato or robinfools. 

**To Reproduce**
1. Put the staff in your offhand.
2.  Go to one of the slots and attempt to use the staff.
3.  Nothing works.
4. (same thing for the alchemy circle and the TP)
(If you aren't sure exactly how it happened, describe what you were doing when the issue occurred instead)

**Expected behavior**
The expected behavior is for the magic staffs to work.
(same thing for the alchemy circle and the TP)

**Screenshots**
I do not have screenshots.

**Time**
10/16/2024 at around 10:30PM EST

**Comment by crux-f** [comment]
This issue was caused by data corruption as a result of automatic backups being set up incorrectly.
It is now resolved.
